<?php
include("./bbdd/conexion.php");

$sentencia_insert = "INSERT INTO `libros` (`autor`, `titulo`, `fecha_alta`, `disponibilidad`) VALUES
('ALLENDE, Isabel','La isla bajo el mar', CURRENT_DATE, 1),
('ASENSI, Matilde ','Venganza en Sevilla', CURRENT_DATE, 1),
('AUSTER, Paul Invisible','Invisible', CURRENT_DATE, 1),
('BOYNE, John ','La casa del propósito especial', CURRENT_DATE, 1),
('BROWN, Dan ','El símbolo perdido', CURRENT_DATE, 1),
('CALDERÓN, Emilio ','La bailarina y el inglés', CURRENT_DATE, 1),
('CASO, Ángeles ','Contra el viento', CURRENT_DATE, 1),
('DUEÑAS, María','El tiempo entre costuras', CURRENT_DATE, 1),
('EBADI, Shirin ','La jaula de oro:  tres hermanos en la pesadilla de la  revolución iraní', CURRENT_DATE, 1),
('GRISHAM, John ','La trampa', CURRENT_DATE, 1),
('IRISARRI, Ángeles de','Perlas para un collar: judias, moras y cristianas en la España medieval', CURRENT_DATE, 1),
('LANDERO, Luis ','Retrato de un hombre inmaduro', CURRENT_DATE, 1),
('LARSSON, Asa ','Aurora Boreal', CURRENT_DATE, 1),
('LEE, Janice Y.K. ','La maestra de piano', CURRENT_DATE, 1),
('LEE, Maureen','Las cuatro hermanas', CURRENT_DATE, 1),
('LEVY, Marc ','Las cosas que no nos dijimos', CURRENT_DATE, 1),
('MARTÍN, Andreu','Barcelona trágica', CURRENT_DATE, 1),
('MENDOZA, Eduardo ','Tres vidas de santos', CURRENT_DATE, 1),
('MONTEAGUDO, David','Fin', CURRENT_DATE, 1),
('MUÑOZ MOLINA, Antonio ','La noche de los tiempos', CURRENT_DATE, 1),
('PANCOL, Katherine ','Los ojos amarillos de los cocodrilos', CURRENT_DATE, 1),
('PEARL, Matthew','El último Dickens', CURRENT_DATE, 1),
('PÉREZ-REVERTE, Arturo','El asedio', CURRENT_DATE, 1),
('RUIZ, Luis Manuel','Tormenta sobre Alejandría', CURRENT_DATE, 1),
('ZIMLER, Richard','El guardián de la aurora', CURRENT_DATE, 1),
('AMMANITI, Niccolò ','Como Dios manda', CURRENT_DATE, 1),
('CAMILLERI, Andrea ','Luna de papel', CURRENT_DATE, 1),
('CASAVELLA, Francisco ','Lo que sé de los vampiros', CURRENT_DATE, 1),
('HARDIE, Titania ','El laberinto de la rosa', CURRENT_DATE, 1),
('IZAGUIRRE, Boris ','Villa Diamante', CURRENT_DATE, 1),
('KING, Jonathon ','El filo azul de la medianoche', CURRENT_DATE, 1),
('LEGUINECHE, Manuel','El club de los faltos de cariño', CURRENT_DATE, 1),
('LEON, Donna ','Líbranos del bien', CURRENT_DATE, 1),
('LESSING, Doris May ','La grieta', CURRENT_DATE, 1),
('LLORÉNS, Chufo','Te daré la tierra', CURRENT_DATE, 1),
('MANKELL, Henning ','Zapatos italianos', CURRENT_DATE, 1),
('MARTÍNEZ DE PISÓN, ','Ignacio Dientes de leche', CURRENT_DATE, 1),
('MASTRETTA, Ángeles','Maridos', CURRENT_DATE, 1),
('MCCARTHY, Cormac ','La carretera', CURRENT_DATE, 1),
('MCEWAN, Ian','Chesil Beach', CURRENT_DATE, 1),
('MENDOZA, Eduardo ','El asombroso viaje de Pomponio Flato', CURRENT_DATE, 1),
('MENDOZA, Élmer','Balas de plata', CURRENT_DATE, 1),
('MONTERO, Rosa','Instrucciones para salvar el mundo', CURRENT_DATE, 1),
('PRADA, Juan Manuel de ','El séptimo velo', CURRENT_DATE, 1),
('RODRÍGUEZ, Antonio Orlando ','Chiquita', CURRENT_DATE, 1),
('RUIZ ZAFÓN, Carlos','El juego del ángel', CURRENT_DATE, 1),
('SÁNCHEZ VIDAL, Agustín ','Nudo de sangre', CURRENT_DATE, 1),
('SMITH, Betty ','Un árbol crece en Brooklyn', CURRENT_DATE, 1),
('SMITH, Tom Rob El niño 44','El niño 44', CURRENT_DATE, 1),
('VOLLMANN, William T. ','Europa central', CURRENT_DATE, 1),
('ÁLVAREZ, María Teresa ','El secreto de Maribárbola', CURRENT_DATE, 1),
('ARIDJIS, Homero','Memorias de un nuevo mundo', CURRENT_DATE, 1),
('BAER, Frank ','El puente de Alcántara', CURRENT_DATE, 1),
('BURGO, Ignacio del','La conspiración del Temple', CURRENT_DATE, 1),
('CHAUVEL, Geneviève ','Saladino: el unificador del Islam', CURRENT_DATE, 1),
('CORNWELL, Bernard ','La batalla del Grial', CURRENT_DATE, 1),
('CORNWELL, Bernard','Excalibur: novela del rey Arturo', CURRENT_DATE, 1),
('DRUON, Maurice','De cómo un rey perdió Francia', CURRENT_DATE, 1),
('DÜBELL, Richard ','Una misa por los Medici', CURRENT_DATE, 1),
('EISEN, Anthony Fon ','Abderramán, el príncipe Omeya', CURRENT_DATE, 1),
('FAST, Howard ','Espartaco', CURRENT_DATE, 1),
('GORDON, Noah','El último judío', CURRENT_DATE, 1),
('HERMARY-VIEILLE, Catherine ','Loca de amor', CURRENT_DATE, 1),
('IRISARRI, Ángeles de','Isabel, la reina. 1, Las hijas de la luna roja', CURRENT_DATE, 1),
('IRISARRI, Ángeles de','Isabel, la reina. 2, El tiempo de la siembra', CURRENT_DATE, 1),
('IRISARRI, Ángeles de ','Isabel, la reina. 3, El sabor de las cerezas', CURRENT_DATE, 1),
('IRISARRI, Ángeles de ','Romance de ciego', CURRENT_DATE, 1),
('LASALA, Magdalena ','Almanzor: el gran guerrero de Al-Ándalus', CURRENT_DATE, 1),
('LECKIE, Ross','Escipión el africano', CURRENT_DATE, 1),
('LORENZO, Javier ','El último soldurio', CURRENT_DATE, 1),
('MOURAD, Kénizé','De parte de la princesa muerta', CURRENT_DATE, 1),
('PUZO, Mario ','Los Borgia', CURRENT_DATE, 1),
('QUERALT, María Pilar','La pasión de la reina', CURRENT_DATE, 1),
('SÁNCHEZ ADALID, Jesús ','El mozárabe', CURRENT_DATE, 1),
('STEINBECK, John','Los hechos del Rey Arturo y sus nobles caballeros', CURRENT_DATE, 1),
('YOURCENAR, Marguerite','Memorias de Adriano', CURRENT_DATE, 1),
('--','1000 trucos para cuidar un bonsái', CURRENT_DATE, 1),
('--','100 enigmas de cifras y de lógica', CURRENT_DATE, 1),
('--','Ajedrez en 20 lecciones para principiantes', CURRENT_DATE, 1),
('--','Cómo aprender papiroflexia', CURRENT_DATE, 1),
('--','Cómo construir dioramas', CURRENT_DATE, 1),
('--','Cómo restaurar muebles antiguos: manual básico para principiantes', CURRENT_DATE, 1),
('--','Cuentas para tus joyas: fáciles de realizar', CURRENT_DATE, 1),
('--','Curso de scrapbooking: el arte de personalizar los recuerdos', CURRENT_DATE, 1),
('--','Decorar la Navidad', CURRENT_DATE, 1),
('--','Découpage', CURRENT_DATE, 1),
('--','Diseña y crea tus joyas', CURRENT_DATE, 1),
('--','El ajedrez: curso completo', CURRENT_DATE, 1),
('--','El gran libro de las manualidades', CURRENT_DATE, 1),
('--','El jardín sin esfuerzo', CURRENT_DATE, 1),
('--','El libro de la encuadernación', CURRENT_DATE, 1),
('--','Fundamentos del ajedrez', CURRENT_DATE, 1),
('--','Juegos de recreación mental para los muy inteligentes', CURRENT_DATE, 1),
('--','Lecciones técnicas de encaje de bolillos', CURRENT_DATE, 1),
('--','Los 100 errores del jardinero y cómo evitarlos', CURRENT_DATE, 1),
('--','Macramé: las más bellas creaciones con el arte de hacer nudos y flecos', CURRENT_DATE, 1),
('--','Manos libres: manualidades fáciles y baratas', CURRENT_DATE, 1),
('--','Pintura decorativa de muebles para principiantes', CURRENT_DATE, 1),
('--','Pintura decorativa, paso a paso', CURRENT_DATE, 1),
('--','Punto de smock: los puntos del bordado sobre frunces explicados paso a paso', CURRENT_DATE, 1),
('--','Velas decorativas', CURRENT_DATE, 1);";

    mysql_query($sentencia_insert);
	echo "Alta realizada correctamente.";

?> 
